### ISSUE TITLE
Use the java JDK binary as default java environment

### ISSUE THREAD

**Issue by hvancamp** [xenit-eu/docker-openjdk#4]
Currently the Java JRE binary is set as the default java environment but that gives issue when one for example is trying to use jmxterm inside the container.

It would be better to use the JDK binary as the default Java environment which is also installed and used to run Alfresco for example.

```
tomcat@f75fa3385dd7:/$ java -jar jmxterm-1.0.0-uber.jar
Welcome to JMX terminal. Type "help" for available commands.
$>open 1
#UnsupportedOperationException: Operation requires JDK instead of JRE
tomcat@f75fa3385dd7:/$ java -version
java version "1.7.0_201"
OpenJDK Runtime Environment (IcedTea 2.6.17) (7u211-2.6.17-0ubuntu0.1)
OpenJDK 64-Bit Server VM (build 24.201-b00, mixed mode)
```

**Comment by anghelutar** [comment]
Which image did you start up? I am trying to reproduce with an isolated java or tomcat image.

**Comment by hvancamp** [comment]
It was using alfresco-enterprise:5.1.5 as baseimage, I believe.

**Comment by anghelutar** [comment]
I could not reproduce, from java 8 onwards (so alfresco 5.1 included) we are installing openjdk - jdk not jre.

**Comment by anghelutar** [comment]
@hvancamp I will move this issue in docker-alfresco, ok?
